{
 "title": "Network Telemetry Lite",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "NE", "query": { "query": "label_values(source)" } },
   {
    "name": "Services",
    "query": {
     "query": "label_values(network_instance_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DC Fabric Throughput",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "interface_traffic_rate_in_bps", "legendFormat": "__auto" },
    {
     "expr": "interface_traffic_rate_out_bps",
     "legendFormat": "{{source}}:{{interface_name}}:OUT"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "platform_control_cpu_total_instant{source=\"$NE\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "platform_control_memory_free{source=\"$NE\"}",
     "legendFormat": "Free "
    },
    {
     "expr": "platform_control_memory_utilization{source=\"$NE\"}",
     "legendFormat": "Utilization"
    },
    {
     "expr": "platform_control_memory_reserved{source=\"$NE\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "platform_control_memory_physical{source=\"$NE\"}",
     "legendFormat": "Physical"
    }
   ]
  },
  {
   "title": "Service: $Services",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_oper_state{network_instance_name='$Services'}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Running SR Linux applications",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "expr": "system_app_management_application_pid{source='$NE'}",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  {
   "title": "Throughput ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "interface_traffic_rate_in_bps{source=\"$NE\"}",
     "legendFormat": "{{interface_name}}:IN"
    },
    {
     "expr": "interface_traffic_rate_out_bps{source=\"$NE\"}",
     "legendFormat": "{{interface_name}}:OUT"
    }
   ]
  }
 ]
}